test

diff --git a/.github/workflows/lark_notification.yml b/.github/workflows/lark_notification.yml
--- a/.github/workflows/lark_notification.yml
+++ b/.github/workflows/lark_notification.yml
@@ -114,22 +114,25 @@ jobs:
               exit 1
             fi
 
-
       - name: deployment_message
         if: ${{ inputs.NEED_APPROVAL == 'false' }}
-        uses: fjogeleit/http-request-action@v1
         continue-on-error: true
-        with:
-          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
-          method: 'POST'
-          bearerToken: ${{ steps.get_tenant_access_token.outputs.tenant_access_token }}
-          customHeaders: '{"Content-Type": "application/json"}'
-          data: |
-            {
+        run:  |
+            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{steps.get_tenant_access_token.outputs.tenant_access_token}}"
+            "https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id" \
+            -d '{
               "receive_id": "${{ inputs.CHANNEL_ID }}",
               "msg_type": "post",
               "content": "${{ steps.deployment_message_parser.outputs.escaped_json }}"
-            }	
+            }	')
+            
+            if [ "$response" -ne 200 ]; then
+              error_message=$(jq -r '.errors' response.json)
+              echo "Failed to retrieve Lark tenant_access_token, error message: $error_message"
+              exit 1
+            fi
 
       - name: Approval Message Preparation
         if: ${{ inputs.NEED_APPROVAL == 'true' }}
@@ -167,16 +170,20 @@ jobs:
 
       - name: Approval Notification
         if: ${{ inputs.NEED_APPROVAL == 'true' }}
-        uses: fjogeleit/http-request-action@v1
         continue-on-error: true
-        with:
-          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
-          method: 'POST'
-          bearerToken: ${{ steps.get_tenant_access_token.outputs.tenant_access_token }}
-          customHeaders: '{"Content-Type": "application/json"}'
-          data: |
-            {
+        run:  |
+            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{steps.get_tenant_access_token.outputs.tenant_access_token}}"
+            "https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id" \
+            -d '{
               "receive_id": "${{ inputs.CHANNEL_ID }}",
               "msg_type": "post",
               "content": "${{ steps.approval_message_parser.outputs.escaped_json }}"
-            }	
+            }')
+            
+            if [ "$response" -ne 200 ]; then
+              error_message=$(jq -r '.errors' response.json)
+              echo "Failed to retrieve Lark tenant_access_token, error message: $error_message"
+              exit 1
+            fi
