test

diff --git a/.github/workflows/lark_notification.yml b/.github/workflows/lark_notification.yml
--- a/.github/workflows/lark_notification.yml
+++ b/.github/workflows/lark_notification.yml
@@ -93,10 +93,10 @@ jobs:
           echo "Escaped One-Line JSON: $one_line_json"
           echo "escaped_json=$one_line_json" >> $GITHUB_OUTPUT	
 
-      - name: get_tenant_ids
-        id: get_tenant_id
+      - name: get_tenant_access_token
+        id: get_tenant_access_token
         run:  |
-            response=$(curl -X POST \
+            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
             -H "Content-Type: application/json" \
             "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal" \
             -d '{
@@ -104,9 +104,16 @@ jobs:
               "app_secret": "${{ secrets.LARK_APP_SECRET }}"
             }')
             
-            echo $response
-            access_token=$(echo "$response" | jq -r .tenant_access_token)
-            echo "tenant_access_token=${access_token}" >> $GITHUB_OUTPUT
+            if [ "$response" -eq 200 ]; then
+              echo $response
+              access_token=$(echo "$response" | jq -r .tenant_access_token)
+              echo "tenant_access_token=${access_token}" >> $GITHUB_OUTPUT
+            else
+              error_message=$(jq -r '.errors' response.json)
+              echo "Failed to retrieve Lark tenant_access_token, error message: $error_message"
+              exit 1
+            fi
+
 
       - name: deployment_message
         if: ${{ inputs.NEED_APPROVAL == 'false' }}
@@ -115,7 +122,7 @@ jobs:
         with:
           url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
           method: 'POST'
-          bearerToken: ${{ steps.get_tenant_id.outputs.tenant_access_token }}
+          bearerToken: ${{ steps.get_tenant_access_token.outputs.tenant_access_token }}
           customHeaders: '{"Content-Type": "application/json"}'
           data: |
             {
@@ -165,7 +172,7 @@ jobs:
         with:
           url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
           method: 'POST'
-          bearerToken: ${{ steps.get_tenant_id.outputs.tenant_access_token }}
+          bearerToken: ${{ steps.get_tenant_access_token.outputs.tenant_access_token }}
           customHeaders: '{"Content-Type": "application/json"}'
           data: |
             {
